### ISSUE TITLE
Check bad county names

### ISSUE THREAD

**Issue by jseppi** [TNRIS/historical-aerials#1]
@ThorTheDestroyer - When importing the old database, I found a number of entries with incorect/dubious county names. I made a mapping of "bad" names to "good" names. Could you please validate?

Please see this file: https://github.com/TNRIS/historical-aerials/blob/master/data/badCounties.csv

The non-obvious ones are 
* Jim Davis -> Jeff Davis
* Cross -> Crosby
* Trinity Basin -> Trinity

**Comment by jseppi** [comment]
Per conversation with @ThorTheDestroyer, everything I have is correct, with the exception of the "Trinity Basin" entry. That entry can actually be removed from the dataset because it is redundant.

**Comment by ThorTheDestroyer** [comment]
That is correct.

**Comment by jseppi** [comment]
ref: 992f15eb5b8d4d9b17e6fb6b27be7195981c47d0
