### ISSUE TITLE
Required and Optional Fields

### ISSUE THREAD

**Issue by jseppi** [TNRIS/historical-aerials#10]
For Record creation and edit, which fields are required and which are optional?
Here is what I have:

* AcquiringAgency - required
* County - required
* Date - required
* IsPublic - required
* IndexType - optional
* LocationCode - optional
* Medium - optional
* PrintType - required
* NumFrames - optional
* Remarks - optional
* Scale - optional
* Coverage - required
* Format - optional
* Mission - optional
* RSDIS - optional

**Comment by ThorTheDestroyer** [comment]
AcquiringAgency - required
County - required
Date - required
IsPublic - required
IndexType - optional
LocationCode - optional
Medium - optional
PrintType - required
NumFrames - required
Remarks - optional
Scale - required
Coverage - required
Format - required
Mission - required
RSDIS - optional

**Comment by jseppi** [comment]
thanks
