### ISSUE TITLE
PrintType choices

### ISSUE THREAD

**Issue by jseppi** [TNRIS/historical-aerials#6]
Can Medium be limited to a set of choices?

Here are the current values in the database:

```
"BOARD" ,
"FILM" ,
"PAPER" ,
"PRINT" ,
"PRNT" ,
"TRANS"
```

Obviously `PRNT` should be amended to `PRINT`.

**Comment by ThorTheDestroyer** [comment]
yes, that will work fine.

**Comment by jseppi** [comment]
I meant "Medium" -- assuming answer still applies

**Comment by ThorTheDestroyer** [comment]
Lets go with 
Board, Film, Paper, Print, Trans,

**Comment by ThorTheDestroyer** [comment]
yeah calling it medium will work

**Comment by jseppi** [comment]
will do
